import pandas as pd
heading = ["S.No","RollNo","Name","Mark","CGPA","Gender"]
df = pd.read_csv("statdata.csv",usecols=heading)
print(df)
print(df.shape)
print(df.head(3))
print(df.describe())
mean1 = df['Mark'].mean()
sum1 = df['Mark'].sum()
max1 = df['Mark'].max()
min1 = df['Mark'].min()
count1 = df['Mark'].count()
median1 = df['Mark'].median()
sd1 = df['Mark'].std()
var1 = df['Mark'].var()
print("\nMean :"+str(mean1))
print("\nSum :"+str(sum1))
print("\nMaximum :"+str(max1))
print("\nMinimum :"+str(min1))
print("\nCount :"+str(count1))
print("\nMedian :"+str(median1))
print("\nStandard Variation :"+str(sd1))
print("\nVariance :"+str(var1))
